## Test Pkl OneHotEncoder and prediction model

In [22]:
import pandas as pd
import numpy as np

# Test Sample
echant_ohe_cat = [['France', 'Female']]
echo_numer =  [[596, 32, 3, 96709.07, 2, 0, 0, 41788.37]]

#### 1) Transform categorical features

In [23]:
# Transform categorical feature
import os
import pickle

# Apply OneHotEncoder 
if os.path.isfile("./OneHotEncoder.pkl"):
  OneHotEncoder = pickle.load(open("./OneHotEncoder.pkl", "rb"))
else:
  raise FileNotFoundError

# Apply the transformation on categorical features
transform = OneHotEncoder.transform(echant_ohe_cat)
transform

array([[1., 0., 0., 1., 0.]])

In [24]:
# Concatenate transform categorical and numeric features 
echo_final = np.concatenate((echo_numer, transform), axis=1)
echo_final

array([[5.960000e+02, 3.200000e+01, 3.000000e+00, 9.670907e+04,
        2.000000e+00, 0.000000e+00, 0.000000e+00, 4.178837e+04,
        1.000000e+00, 0.000000e+00, 0.000000e+00, 1.000000e+00,
        0.000000e+00]])

#### 2) Apply machine learning pkl model

In [25]:
# Apply machine learning pkl model

# Unpickle our model so we can use it!
if os.path.isfile("./model.pkl"):
  model = pickle.load(open("./model.pkl", "rb"))
else:
  raise FileNotFoundError

prediction = model.predict(echo_final)
prediction

array([0])

In [31]:
if prediction[0] == 0:
    print("This customer is more likely to cancel the subscription !")
else:
    print("No")

This customer is more likely to cancel the subscription !
